---
title: "thank_you_email"
format: html
---

```{r}
library(googlesheets4)
library(blastula)
library(tidyverse)
ss <- "https://docs.google.com/spreadsheets/d/18wAjNf2iROcjmqxMbuCYYjPOIsXcY4FxOzKBwyR_ZqU/edit#gid=1969315070"
```

```{r}
img_string <- add_image(file = "~/GitHub/midnightsun_swing/midnightsunswing.jpeg")
```

```{r}
email <- str_glue("Thanks for attending the **Midnight Sun Swing Festival - 1st Ed**

Thanks for bringing your smiles and your positive energy, you really made the weekend feel cozy and inviting for everyone.

Thanks to everyone who helped with this event in any way. <br> We truly felt the support of the entire community from the moment registration opened.

We hope that you enjoyed the weekend, got some fresh inspiration, maybe a new move or two, maybe some new friends.

**And we would really appreciate if you could spare 5 min to give us your feedback, it will help us shape future events ;)**

[FEEDBACK FORM LINK](https://forms.gle/48UqEgDuQeBHY2Ej7)

Cheers from the Midnight Sun Swing Team

{img_string}
")
```

```{r}
thanksemails <- read_sheet(ss, sheet = "Thankyou") %>% filter(!is.na(email))
thanksemails <- thanksemails$email
```


```{r}
email_to_send <- compose_email(
    body = md(email),
    title = "Thanks for coming to Midnight Sun Swing",
    footer = "Midnight Sun Swing"
    )

email_to_send 

batch1 <- thanksemails[1:50]
batch2 <- thanksemails[51:100]
batch3 <- thanksemails[101:150]
batch4 <- thanksemails[151:185]

smtp_send(
  email_to_send,
  to = "midnightsunswing@gmail.com",
  bcc = "minna.yliollila@gmail.com",
  from = c("Midnight Sun Swing" = "midnightsunswing@gmail.com"),
  subject = "Thank you - Midnight Sun Swing",
  credentials = creds_file(file = "~/gmail_creds")
  )
```

